perft: perft.cpp ../reasoner.cpp ../reasoner.hpp
	g++ perft.cpp ../reasoner.cpp -std=c++17 -Ofast -flto -march=native -o perft
simulations: simulations.cpp ../reasoner.cpp ../reasoner.hpp
	g++ simulations.cpp ../reasoner.cpp -std=c++17 -Ofast -flto -march=native -o simulations
