"""Apply some modifications on AST generated by interpreter

* Capitalize name of each type
* Add underscore to each symbol which is same as any C++ keyword
"""

import json
import argparse


ID_LABEL = "identifier"
ID_LABELS = "identifiers"
SYMBOL_LABEL = "symbol"
KIND_LABEL = "kind"
TARGET_KINDS = ["TypeReference", "TypeDeclaration"]

KEYWORDS = [
    "alignas",
    "alignof",
    "and",
    "and_eq",
    "asm",
    "atomic_cancel",
    "atomic_commit",
    "atomic_noexcept",
    "auto",
    "bitand",
    "bitor",
    "bool",
    "break",
    "case",
    "catch",
    "char",
    "char16_t",
    "char32_t",
    "char8_t",
    "class",
    "co_await",
    "co_return",
    "co_yield",
    "compl",
    "concept",
    "const",
    "const_cast",
    "consteval",
    "constexpr",
    "constinit",
    "continue",
    "decltype",
    "default",
    "delete",
    "do",
    "double",
    "dynamic_cast",
    "else",
    "enum",
    "explicit",
    "export",
    "extern",
    "false",
    "float",
    "for",
    "friend",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "mutable",
    "namespace",
    "new",
    "noexcept",
    "not",
    "not_eq",
    "nullptr",
    "operator",
    "or",
    "or_eq",
    "private",
    "protected",
    "public",
    "reflexpr",
    "register",
    "reinterpret_cast",
    "requires",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "static_assert",
    "static_cast",
    "struct",
    "switch",
    "synchronized",
    "template",
    "this",
    "thread_local",
    "throw",
    "true",
    "try",
    "typedef",
    "typeid",
    "typename",
    "union",
    "unsigned",
    "using",
    "virtual",
    "void",
    "volatile",
    "wchar_t",
    "while",
    "xor",
    "xor_eq",
]


def should_modify_type_name(name):
    return name[0].islower()


def get_modified_type_name(name):
    return name.title()


def get_type_name_modifications(ast_json):
    type_name_modifications = dict()
    for type_declaration in ast_json["types"]:
        type_name = type_declaration[ID_LABEL]
        if should_modify_type_name(type_name):
            type_name_modifications[type_name] = get_modified_type_name(type_name)
    return type_name_modifications


def apply_modifications(ast_json, type_name_modifications):
    if isinstance(ast_json, dict):
        # fix keywords
        if ID_LABEL in ast_json and ast_json[ID_LABEL] in KEYWORDS:
            ast_json[ID_LABEL] = f"{ast_json[ID_LABEL]}_"
        if SYMBOL_LABEL in ast_json and ast_json[SYMBOL_LABEL] in KEYWORDS:
            ast_json[SYMBOL_LABEL] = f"{ast_json[SYMBOL_LABEL]}_"
        if ID_LABELS in ast_json:
            ast_json[ID_LABELS] = [f"{id}_" if id in KEYWORDS else id for id in ast_json[ID_LABELS]]
        # fix types
        if ID_LABEL in ast_json and KIND_LABEL in ast_json:
            if ast_json[ID_LABEL] in type_name_modifications and ast_json[KIND_LABEL] in TARGET_KINDS:
                ast_json[ID_LABEL] = type_name_modifications[ast_json[ID_LABEL]]
        for item in ast_json.values():
            apply_modifications(item, type_name_modifications)
    elif isinstance(ast_json, list):
        for item in ast_json:
            apply_modifications(item, type_name_modifications)


parser = argparse.ArgumentParser(description="Adjust RG AST to compiler")
parser.add_argument("input", nargs=1, help="input JSON file with AST")
parser.add_argument("output", nargs=1, help="output JSON file with AST")

args = parser.parse_args()
input_file = args.input[0]
output_file = args.output[0]

with open(input_file, "r") as json_file:
    ast_json = json.load(json_file)

type_name_modifications = get_type_name_modifications(ast_json)
apply_modifications(ast_json, type_name_modifications)

with open(output_file, "w") as json_file:
    json.dump(ast_json, json_file, indent=4)
